spring:
  freemarker:
    cache: false
    settings:
      auto_import: /_imports/layout.ftlh as l
      output_encoding: UTF-8
  datasource:
    url: jdbc:h2:file:./data/swiss_tracker;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;COLLATION=CZECH
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console