[#ftl]

[#macro page]
    <!DOCTYPE html>
    <html lang="cs">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Swiss Tracker</title>
        <link rel="stylesheet" href="./style.css" type="text/css"/>
    </head>
    <body>
    <main>
            <h1>Welcome to the Tournament!</h1>
    </main>
    </body>
    </html>
[/#macro]